import 'regenerator-runtime/runtime'
import { LoaderCustom, SideBarCustom, ToastCustom } from '@/components'
import { PageLayoutBaseModel } from '@/models'
import '@/styles/globals.css'
import { useFirstSetupApp } from '@/utils/hooks'
import { AppProps } from 'next/app'
import Head from 'next/head'
import { FC } from 'react'
import { QueryClient, QueryClientProvider } from 'react-query'
import { ReactQueryDevtools } from 'react-query/devtools'
import { RecoilRoot } from 'recoil'

const queryClient = new QueryClient()

type AppPropsWithLayout = AppProps & {
  Component: PageLayoutBaseModel
}
const App: FC<AppPropsWithLayout> = ({ Component, pageProps }) => {
  useFirstSetupApp()

  return (
    <>
      <Head>
        <title>Meva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RecoilRoot>
        <QueryClientProvider client={queryClient}>
          {!!Component.getLayout ? (
            Component.getLayout(<Component {...pageProps} />)
          ) : (
            <SideBarCustom>
              <Component {...pageProps} />
            </SideBarCustom>
          )}

          <LoaderCustom />
          <ToastCustom />

          <ReactQueryDevtools initialIsOpen={false} position="bottom-right" />
        </QueryClientProvider>
      </RecoilRoot>
    </>
  )
}

export default App
